name: eie3117
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.12.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - dav1d=1.2.1
  - expat=2.7.3
  - fontconfig=2.15.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icu=73.1
  - jpeg=9f
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libglib=2.86.3
  - libgomp=15.2.0
  - libiconv=1.16
  - libnsl=2.0.0
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=1.41.5
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.1.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.10.1
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - asgiref==3.11.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cryptography==46.0.4
      - defusedxml==0.7.1
      - django==5.2.10
      - django-cors-headers==4.9.0
      - django-extensions==4.1
      - djangorestframework==3.16.1
      - djangorestframework-simplejwt==5.5.1
      - djoser==2.3.3
      - idna==3.11
      - oauthlib==3.3.1
      - pycparser==3.0
      - pyjwt==2.11.0
      - python3-openid==3.2.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - social-auth-app-django==5.7.0
      - social-auth-core==4.8.3
      - sqlparse==0.5.5
      - typing-extensions==4.15.0
      - urllib3==2.6.3
